name: CI
run-name: CI triggered by @${{ github.actor }}

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci-checks:
    name: Run checks on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: make venv
      - run: make lint
      - run: make test
