name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv

    - name: Install deps
      run: |
        make install

    - name: Run lint
      run: |
        make lint

    - name: Run test
      run: |
        make test
